# Generated by Django 3.0 on 2023-07-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
