# Generated by Django 3.0 on 2023-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apreg',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('sap', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tsreg',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('ste', models.CharField(max_length=15)),
            ],
        ),
    ]
