# Generated by Django 3.0 on 2023-07-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_apreg_tsreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollsap',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('td', models.IntegerField()),
                ('ys', models.IntegerField()),
                ('no', models.IntegerField()),
            ],
        ),
    ]
