# Generated by Django 3.0 on 2023-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pollsap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollsts',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('tr', models.IntegerField()),
                ('co', models.IntegerField()),
                ('bj', models.IntegerField()),
            ],
        ),
    ]
