# Generated by Django 3.0 on 2024-02-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pollsts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apreg',
        ),
        migrations.DeleteModel(
            name='Pollsap',
        ),
        migrations.DeleteModel(
            name='Pollsts',
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
        migrations.DeleteModel(
            name='Tsreg',
        ),
    ]
