# Generated by Django 3.0 on 2024-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0007_auto_20240227_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apreg',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('sap', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pollsap',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('td', models.IntegerField()),
                ('ys', models.IntegerField()),
                ('no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pollsts',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('tr', models.IntegerField()),
                ('co', models.IntegerField()),
                ('bj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=15)),
                ('em', models.CharField(max_length=15)),
                ('sap', models.CharField(max_length=15)),
                ('ste', models.CharField(max_length=15)),
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tsreg',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('ste', models.CharField(max_length=15)),
            ],
        ),
    ]
